/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ModelService } from "../model.service";
import { ModelCreateInput } from "./ModelCreateInput";
import { ModelWhereInput } from "./ModelWhereInput";
import { ModelWhereUniqueInput } from "./ModelWhereUniqueInput";
import { ModelFindManyArgs } from "./ModelFindManyArgs";
import { ModelUpdateInput } from "./ModelUpdateInput";
import { Model } from "./Model";
import { TrainingJobFindManyArgs } from "../../trainingJob/base/TrainingJobFindManyArgs";
import { TrainingJob } from "../../trainingJob/base/TrainingJob";
import { TrainingJobWhereUniqueInput } from "../../trainingJob/base/TrainingJobWhereUniqueInput";
import { PredictionFindManyArgs } from "../../prediction/base/PredictionFindManyArgs";
import { Prediction } from "../../prediction/base/Prediction";
import { PredictionWhereUniqueInput } from "../../prediction/base/PredictionWhereUniqueInput";

export class ModelGrpcControllerBase {
  constructor(protected readonly service: ModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Model })
  @GrpcMethod("ModelService", "createModel")
  async createModel(@common.Body() data: ModelCreateInput): Promise<Model> {
    return await this.service.createModel({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        accuracy: true,
        name: true,
        version: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Model] })
  @ApiNestedQuery(ModelFindManyArgs)
  @GrpcMethod("ModelService", "models")
  async models(@common.Req() request: Request): Promise<Model[]> {
    const args = plainToClass(ModelFindManyArgs, request.query);
    return this.service.models({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        accuracy: true,
        name: true,
        version: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModelService", "model")
  async model(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    const result = await this.service.model({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        accuracy: true,
        name: true,
        version: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModelService", "updateModel")
  async updateModel(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() data: ModelUpdateInput
  ): Promise<Model | null> {
    try {
      return await this.service.updateModel({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          accuracy: true,
          name: true,
          version: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModelService", "deleteModel")
  async deleteModel(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    try {
      return await this.service.deleteModel({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          accuracy: true,
          name: true,
          version: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/trainingJobs")
  @ApiNestedQuery(TrainingJobFindManyArgs)
  @GrpcMethod("ModelService", "findManyTrainingJobs")
  async findManyTrainingJobs(
    @common.Req() request: Request,
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<TrainingJob[]> {
    const query = plainToClass(TrainingJobFindManyArgs, request.query);
    const results = await this.service.findTrainingJobs(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        endTime: true,
        startTime: true,

        model: {
          select: {
            id: true,
          },
        },

        dataset: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trainingJobs")
  @GrpcMethod("ModelService", "connectTrainingJobs")
  async connectTrainingJobs(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: TrainingJobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingJobs: {
        connect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trainingJobs")
  @GrpcMethod("ModelService", "updateTrainingJobs")
  async updateTrainingJobs(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: TrainingJobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingJobs: {
        set: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trainingJobs")
  @GrpcMethod("ModelService", "disconnectTrainingJobs")
  async disconnectTrainingJobs(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: TrainingJobWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingJobs: {
        disconnect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/predictions")
  @ApiNestedQuery(PredictionFindManyArgs)
  @GrpcMethod("ModelService", "findManyPredictions")
  async findManyPredictions(
    @common.Req() request: Request,
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Prediction[]> {
    const query = plainToClass(PredictionFindManyArgs, request.query);
    const results = await this.service.findPredictions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        inputData: true,
        outputData: true,
        predictedAt: true,

        model: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/predictions")
  @GrpcMethod("ModelService", "connectPredictions")
  async connectPredictions(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: PredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      predictions: {
        connect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/predictions")
  @GrpcMethod("ModelService", "updatePredictions")
  async updatePredictions(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: PredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      predictions: {
        set: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/predictions")
  @GrpcMethod("ModelService", "disconnectPredictions")
  async disconnectPredictions(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: PredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      predictions: {
        disconnect: body,
      },
    };
    await this.service.updateModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
