/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Model } from "./Model";
import { ModelCountArgs } from "./ModelCountArgs";
import { ModelFindManyArgs } from "./ModelFindManyArgs";
import { ModelFindUniqueArgs } from "./ModelFindUniqueArgs";
import { CreateModelArgs } from "./CreateModelArgs";
import { UpdateModelArgs } from "./UpdateModelArgs";
import { DeleteModelArgs } from "./DeleteModelArgs";
import { TrainingJobFindManyArgs } from "../../trainingJob/base/TrainingJobFindManyArgs";
import { TrainingJob } from "../../trainingJob/base/TrainingJob";
import { PredictionFindManyArgs } from "../../prediction/base/PredictionFindManyArgs";
import { Prediction } from "../../prediction/base/Prediction";
import { ModelService } from "../model.service";
@graphql.Resolver(() => Model)
export class ModelResolverBase {
  constructor(protected readonly service: ModelService) {}

  async _modelsMeta(
    @graphql.Args() args: ModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Model])
  async models(@graphql.Args() args: ModelFindManyArgs): Promise<Model[]> {
    return this.service.models(args);
  }

  @graphql.Query(() => Model, { nullable: true })
  async model(
    @graphql.Args() args: ModelFindUniqueArgs
  ): Promise<Model | null> {
    const result = await this.service.model(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Model)
  async createModel(@graphql.Args() args: CreateModelArgs): Promise<Model> {
    return await this.service.createModel({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Model)
  async updateModel(
    @graphql.Args() args: UpdateModelArgs
  ): Promise<Model | null> {
    try {
      return await this.service.updateModel({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Model)
  async deleteModel(
    @graphql.Args() args: DeleteModelArgs
  ): Promise<Model | null> {
    try {
      return await this.service.deleteModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [TrainingJob], { name: "trainingJobs" })
  async findTrainingJobs(
    @graphql.Parent() parent: Model,
    @graphql.Args() args: TrainingJobFindManyArgs
  ): Promise<TrainingJob[]> {
    const results = await this.service.findTrainingJobs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Prediction], { name: "predictions" })
  async findPredictions(
    @graphql.Parent() parent: Model,
    @graphql.Args() args: PredictionFindManyArgs
  ): Promise<Prediction[]> {
    const results = await this.service.findPredictions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
