/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumModelStatus } from "./EnumModelStatus";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TrainingJobListRelationFilter } from "../../trainingJob/base/TrainingJobListRelationFilter";
import { PredictionListRelationFilter } from "../../prediction/base/PredictionListRelationFilter";

@InputType()
class ModelWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumModelStatus,
  })
  @IsEnum(EnumModelStatus)
  @IsOptional()
  @Field(() => EnumModelStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  accuracy?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  version?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TrainingJobListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TrainingJobListRelationFilter)
  @IsOptional()
  @Field(() => TrainingJobListRelationFilter, {
    nullable: true,
  })
  trainingJobs?: TrainingJobListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PredictionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PredictionListRelationFilter)
  @IsOptional()
  @Field(() => PredictionListRelationFilter, {
    nullable: true,
  })
  predictions?: PredictionListRelationFilter;
}

export { ModelWhereInput as ModelWhereInput };
