/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ModelService } from "../model.service";
import { ModelCreateInput } from "./ModelCreateInput";
import { Model } from "./Model";
import { ModelFindManyArgs } from "./ModelFindManyArgs";
import { ModelWhereUniqueInput } from "./ModelWhereUniqueInput";
import { ModelUpdateInput } from "./ModelUpdateInput";

export class ModelControllerBase {
  constructor(protected readonly service: ModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Model })
  async createModel(@common.Body() data: ModelCreateInput): Promise<Model> {
    return await this.service.createModel({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Model] })
  @ApiNestedQuery(ModelFindManyArgs)
  async models(@common.Req() request: Request): Promise<Model[]> {
    const args = plainToClass(ModelFindManyArgs, request.query);
    return this.service.models({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async model(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    const result = await this.service.model({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateModel(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() data: ModelUpdateInput
  ): Promise<Model | null> {
    try {
      return await this.service.updateModel({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteModel(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    try {
      return await this.service.deleteModel({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
